### ISSUE TITLE
Sudden death / tie breaker

### ISSUE THREAD

**Issue by JetBoom** [JetBoom/extremefootballthrowdown#31]
Two possibilities:

A. No respawning or switching teams (all new joiners go on spectator). One score or total knockout to win. Time limit of 4 minutes. If the time runs out then the map starts shrinking, akin to the tie breaker in shootmania. Touch the edge and you get KO'd. If by some miracle both teams are KO'd on the same frame then it'll truly be a tie. Box bounds can be calculated by using the average of both team's spawn point positions.

B. Finish the street fighting minigame thing that is basically already coded. Problem is that collisions are crappy and there's the (high on some maps) possibility that the fight location would be placed inside a wall or in the air.

SUDDEN DEATH should be in big letters on everyone's screen.

**Comment by dissident93** [comment]
I believe the majority of the EFT community would prefer the first suggestion, since it would still rely on what they know how to do, but with the added risk of not being killed or letting a touchdown be scored. Perhaps you could integrate the minigame into that somehow?

**Comment by Maddenn** [comment]
Are there any plans to continue this? Assuming so, my suggestion would be:

- 5 Minute OT.
- Sudden Death, first to score wins.
- Beatdown Sticks and Big Poles are the only items that spawn.
- In the last minute, rather than the map shrinking, have RAGE! Ball activated for both teams instead.
- If neither teams scores in 5 Minutes it would result in a tie.

This would be similar to the old one in the Publish Queue but balance it out on the flatter maps like Blood Bowl and Soccer where RAGE! is pretty much an instant touchdown.

**Comment by JetBoom** [comment]
7df77d1d031e7463d2619be89822408861aa4cd7
